FROM node:16.20.1-alpine 

WORKDIR /usr/src/app

COPY ./package*.json ./

RUN --mount=type=cache,target=/usr/src/app/.npm \
    npm set cache /usr/src/app/.npm && \
    npm install

COPY . .

EXPOSE 3000

CMD ["npm", "start"]

